### ISSUE TITLE
Secure Method to Pass Database Credentials to API and Director Deployments

### ISSUE THREAD

**Issue by olivereri** [sorry-cypress/charts#126]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
When using an external DB (i.e. AWS DocumentDB) `mongodb.mongoConnectionString` should have an option to use secret values. 

## Why is it needed? What is the value? For whom do we build it?
Our organization is strict about not committing secrets or credentials to a git repository. Our organization likely isn't the only one to benefit from this feature. The Department of Veterans Affair's.

## High-level feature overview
There doesn't appear to be a straightforward way to provide DB credentials when using an external DB without committing them to a repository in `values.yaml`.  I think the correct pattern to hookup the Director and API to AWS DocumentDB is to use the provided application connection string. The difficultly with this is that it contains the username and password in it. Additionally, I see that I can use values from the upstream helm chart, but setting `auth.rootuser` and `auth.rootpassword` exposes these secrets in values.yaml.

Allowing the respective deployment objects to pull from a `secretKeyRef` would make this more secure.

## Other
We're using ArgoCD and committing Helm Charts and Values to a shared application manifest repository. It's likely I'm completely ignorant on how to deliver these credentials securely to Sorry-Cypress without a feature request.

**Comment by tico24** [comment]
While I 100% agree with the theory, this is beyond the scope of this helm chart, mostly because Helm absolutely sucks at secrets management. By all means, push a PR to optionally use Kubernetes secrets for certain values.. but that doesn't actually solve the issue, because k8s secrets aren't really that secret either.

However, you're in luck. I happen to be an Argo CD contributor, and you should be solving your secrets management issues at the Argo CD level. 

I co-wrote this Argo CD plugin: https://github.com/crumbhole/argocd-vault-replacer

But there are many other options: https://akuity.io/blog/how-to-manage-kubernetes-secrets-gitops/
